/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. */
/* Generated by: node tools/generate-routes.js */

export const ROUTE_MANIFEST: Record<string, () => Promise<any>> = {
  "/admin/user-setup/user-list": () => import("../../features/administration/pages/administration-users-page/administration-users-page.component").then(m => m.AdministrationUsersPageComponent),
};
