const fs = require('fs');
const path = require('path');

const out = path.join(__dirname, '..', 'src', 'app', 'core', 'routing', 'routes.generated.ts');

const content = `/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. */
/* Generated by: node tools/generate-routes.js */

export const ROUTE_MANIFEST: Record<string, () => Promise<any>> = {
  "/administration/company-setup/adm-company-info": () => import("../../features/administration/Companysetup/adm-company-info/pages/adm-company-info-list/adm-company-info-list.component").then(m => m.AdmCompanyInfoListComponent),
};
`;

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, content, 'utf8');

console.log('[OK] wrote routes.generated.ts');