/* tools/generate-routes.js
 * Scans all page components for:
 *   export const DB_ROUTE = '/some/path';
 * Then generates:
 *   src/app/core/routing/routes.generated.ts
 */

const fs = require("fs");
const path = require("path");

const ROOT = process.cwd();
const APP_DIR = path.join(ROOT, "src", "app");
const FEATURES_DIR = path.join(APP_DIR, "features");
const OUT_DIR = path.join(APP_DIR, "core", "routing");
const OUT_FILE = path.join(OUT_DIR, "routes.generated.ts");

function walk(dir, files = []) {
  if (!fs.existsSync(dir)) return files;
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    const st = fs.statSync(full);
    if (st.isDirectory()) walk(full, files);
    else files.push(full);
  }
  return files;
}

function toPosix(p) {
  return p.replace(/\\/g, "/");
}

const all = walk(FEATURES_DIR)
  .filter(f => f.includes(`${path.sep}pages${path.sep}`))
  .filter(f => f.endsWith(".component.ts"));

const entries = [];

for (const file of all) {
  const text = fs.readFileSync(file, "utf8");

  const routeMatch = text.match(/export\s+const\s+DB_ROUTE\s*=\s*['"`]([^'"`]+)['"`]\s*;/);
  if (!routeMatch) continue;

  const route = routeMatch[1].trim();

  const classMatch = text.match(/export\s+class\s+([A-Za-z0-9_]+)\s*/);
  if (!classMatch) continue;

  const className = classMatch[1];

  const relFromApp = toPosix(path.relative(APP_DIR, file)).replace(/\.ts$/, "");
  const importPath = `../../${relFromApp}`;

  entries.push({ route, className, importPath });
}

entries.sort((a, b) => a.route.localeCompare(b.route));

fs.mkdirSync(OUT_DIR, { recursive: true });

const lines = [];
lines.push("/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. */");
lines.push("/* Generated by: node tools/generate-routes.js */");
lines.push("");
lines.push("export const ROUTE_MANIFEST: Record<string, () => Promise<any>> = {");

for (const e of entries) {
  lines.push(`  "${e.route}": () => import("${e.importPath}").then(m => m.${e.className}),`);
}

lines.push("};");
lines.push("");

fs.writeFileSync(OUT_FILE, lines.join("\n"), "utf8");

console.log(`✅ routes.generated.ts created`);
console.log(`✅ total routes: ${entries.length}`);
console.log(`📄 ${OUT_FILE}`);